# Generated by Django 4.1.2 on 2024-06-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio01', '0002_producto_color_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
