# Generated by Django 4.1.2 on 2024-05-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio01', '0002_producto_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/producto-1.png', upload_to='productos/'),
        ),
    ]
