# Generated by Django 4.1.2 on 2024-06-10 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('negocio01', '0003_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio01.usuario')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='color',
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id_orden_item', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='negocio01.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio01.producto')),
            ],
        ),
    ]
